version: '3.8'

services: 
  node_backend:
    container_name: node_tabnine
    image: node_tabnine:0.0.4
    build: 
      context: .
    ports:
      - "8000:8000"
    environment: 
      - EXTERNAL_PORT=8000
      - PGDATABASE=tabnine_db
      - PGUSER=luis
      - PGPASSWORD=123
      - PGHOST=node_db
    depends_on: 
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tabnine_db
    volumes:
      - nps_data:/data/db

volumes:
  nps_data: {}